[workspace.package]
version = "0.1.0"
description = "prototypes"

[workspace]
members = [
    "projects/networking/slp-01",
    "projects/networking/network-handler"
    ]
resolver = "2"

[profile.release]
opt-level = "z"
strip = true
lto = true
codegen-units = 1
panic = "abort"
